from __future__ import annotations

import argparse
import difflib
import inspect
import re
import sys
from pathlib import Path
from typing import Any, get_overloads

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import annplyr  # noqa: E402
import annplyr.typing as annplyr_typing  # noqa: E402

TARGET = ROOT / "docs" / "development" / "public-typing-contract.md"


def _public_methods(cls: type[Any]) -> list[tuple[str, Any]]:
    return [
        (name, value)
        for name, value in inspect.getmembers(cls)
        if callable(value) and (not name.startswith("_") or name == "__iter__")
    ]


def _format(value: Any) -> str:
    stable = re.sub(r"<object object at 0x[0-9a-fA-F]+>", "<sentinel>", str(value))
    stable = stable.replace("anndata._core.anndata.AnnData", "anndata.AnnData")
    stable = stable.replace("pandas.core.frame.DataFrame", "pandas.DataFrame")
    return stable.replace("|", r"\|").replace("\n", " ")


def _signature(value: Any) -> tuple[str, str]:
    try:
        signature = inspect.signature(value, eval_str=False)
    except (TypeError, ValueError):
        return "-", type(value).__name__
    returned = signature.return_annotation
    if returned is inspect.Signature.empty:
        return str(signature), "class instance" if inspect.isclass(value) else "missing"
    return str(signature), str(returned)


def _callable_rows(surface: str, values: list[tuple[str, Any]]) -> list[str]:
    rows: list[str] = []
    for name, value in values:
        overloads = get_overloads(value)
        for index, overload in enumerate(overloads, start=1):
            signature, returned = _signature(overload)
            rows.append(
                f"| {surface} | `{name}` overload {index} | overload | `{_format(signature)}` | `{_format(returned)}` |"
            )
        signature, returned = _signature(value)
        kind = "class" if inspect.isclass(value) else "callable"
        rows.append(f"| {surface} | `{name}` | {kind} | `{_format(signature)}` | `{_format(returned)}` |")
    return rows


def render() -> str:
    """Render the complete public typing inventory as Markdown."""
    root_callables: list[tuple[str, Any]] = []
    root_values: list[str] = []
    for name in sorted(annplyr.__all__):
        value = getattr(annplyr, name)
        if callable(value):
            root_callables.append((name, value))
        else:
            root_values.append(
                f"| root | `{name}` | {type(value).__name__} value | `-` | `{type(value).__module__}.{type(value).__qualname__}` |"
            )

    rows = [
        *_callable_rows("root", root_callables),
        *root_values,
        *_callable_rows("accessor", _public_methods(annplyr.AnnplyrAccessor)),
        *_callable_rows("grouped", _public_methods(annplyr.GroupedAnnData)),
    ]

    alias_rows: list[str] = []
    for name in annplyr_typing.__all__:
        value = getattr(annplyr_typing, name)
        if name == "AnnDataWithAnnplyr":
            definition = "typing-only AnnData subtype with ap; runtime alias of anndata.AnnData"
        elif hasattr(value, "__value__"):
            definition = repr(value.__value__)
        else:
            definition = repr(value)
        alias_rows.append(f"| `{name}` | `{_format(definition)}` |")

    return "\n".join(
        [
            "# Public typing contract",
            "",
            "This file is generated by `scripts/render_typing_contract.py`. It inventories every root export, public accessor and grouped method, registered overload, return annotation, and supported alias. Run the script with `--write` after an intentional public typing change.",
            "",
            "## Symbols and methods",
            "",
            "| Surface | Symbol | Kind | Signature | Return |",
            "|---|---|---|---|---|",
            *rows,
            "",
            "## Consumer aliases",
            "",
            "| Alias | Definition |",
            "|---|---|",
            *alias_rows,
            "",
        ]
    )


def main() -> int:
    """Write or verify the committed typing inventory."""
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        TARGET.write_text(rendered)
        return 0
    current = TARGET.read_text() if TARGET.exists() else ""
    if current == rendered:
        return 0
    sys.stderr.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile=str(TARGET),
            tofile="generated",
        )
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
